language: bash

sudo: false

addons:
  apt:
#    sources:
#    - debian-jessie
    packages:
    - shellcheck

script:
 - shellcheck -s bash ./backup.sh

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGdyaWdydXNzJTNBbWF0cml4Lm9yZy8lMjFtemloTmR5aWhORU9iWVZDWUklM0FtYXRyaXgub3Jn"
        on_success: always  # always|never|change
        on_failure: always
        on_start: never
