#!/bin/bash
TARGETS="/etc/httpd/conf /var/www"
LIST=""
for i in $TARGETS
do
	echo "$i"
    L=$(find "$i" -type f -mtime -300)
    LIST="$LIST
$L"
done
#echo $LIST
#LL="
#"
#    LIST="${LIST//$LL/ }"
#    echo "$LIST"
tar -cvf - $LIST | xz -9 --threads=0 - > "${d}backup.tar.xz"
